server:
    port: 8080
    servlet:
        context-path: /cliente

spring:
    liquibase:
        enabled: true
        change-log: classpath:/db/db-changelog-master.xml
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
    datasource:
        url: 'jdbc:postgresql://localhost:5432/clientedb'
        username: clienteuser
        password: clientepwd
        driver-class-name: org.postgresql.Driver
        platform: org.hibernate.dialect.PostgreSQLDialect
        
swagger:
    title: Cliente Service
    description: Serviço de manipulação do cliente