server:
    port: 8080

spring:
    h2:
      console:
        enabled: true
    datasource:
        platform: h2
        url: 'jdbc:h2:file:../database/clientdb'
        username: sa
        password:
        driver-class-name: org.h2.Driver  
       
