server:
    port: 8080
    servlet:
        context-path: /cliente

spring:
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
    datasource:
        url: 'jdbc:postgresql://localhost:5432/clientedb'
        username: clienteuser
        password: clientepwd
        driver-class-name: org.postgresql.Driver
        
swagger:
    title: Cliente Service
    description: Serviço de manipulação do cliente